#!/bin/bash

TOOLS_DIR=`dirname $0`

APP_DIR=.

if [ $# -eq 1 ]; then
	APP_DIR=$1
fi

echo "Updating pails app in $APP_DIR"

mkdir -p $APP_DIR || exit 1

# Don't overwrite the layout/controllers/etc. OR the .htaccess file
#cp -r $TOOLS_DIR/../default/* $APP_DIR/
#cp -r $TOOLS_DIR/../default/.htaccess $APP_DIR/ #Make sure we got the .htaccess file for apache

# No one should be touching the contents of lib/pails
mkdir -p $APP_DIR/lib/pails
cp -r $TOOLS_DIR/../*.php $APP_DIR/lib/pails/
cp -r $TOOLS_DIR/../lib $APP_DIR/lib/pails/

#$GIT_COMMAND https://github.com/jpfuentes2/php-activerecord.git lib/php-activerecord