#!/bin/bash

PAILS_PATH=`which $0`
while [ -L $PAILS_PATH ]; do
	PAILS_PATH=`readlink $PAILS_PATH`
done
TOOLS_DIR=`dirname $PAILS_PATH`
COMMAND=$1

shift

case $COMMAND in
	'n'|'ne'|'new')
		$TOOLS_DIR/pails-new $@
		;;
	'u'|'up'|'upd'|'upda'|'updat'|'update')
		$TOOLS_DIR/pails-update $@
		;;
	's'|'se'|'ser'|'serv'|'serve'|'server')
		$TOOLS_DIR/pails-server $@
		;;
	*)
		echo "Unknown command $COMMAND"
		;;
esac