#!/bin/bash

TOOLS_DIR=`dirname $0`

APP_DIR=.
APP_NAME='default'
APP_NAME_TC='Default'

if [ $# -eq 1 ]; then
	APP_DIR=$1
    APP_NAME=`echo $1 | awk '{print tolower($0)}'`
    APP_NAME_TC=`echo $1 | awk '{printf("%s%s",toupper(substr($0,1,1)),substr($0,2))}'`
fi

echo "Creating new pails app in $APP_DIR"

mkdir -p $APP_DIR || exit 1

cp -r $TOOLS_DIR/../default/* $APP_DIR/
cp -r $TOOLS_DIR/../default/.htaccess $APP_DIR/ #Make sure we got the .htaccess file for apache

# Make directory for template
mkdir -p $APP_DIR/views/$APP_NAME
# Empty view file
touch $APP_DIR/views/$APP_NAME/index.php

# Edit default controller to match applications name
pushd $APP_DIR/controllers > /dev/null
mv DefaultController.php ${APP_NAME_TC}Controller.php
sed -E -i .old "s/DefaultController/${APP_NAME_TC}Controller/g" ${APP_NAME_TC}Controller.php
rm *.old
popd > /dev/null

# Edit config's app name
pushd $APP_DIR/config > /dev/null
sed -E -i .old "s:APP_NAME = '':APP_NAME = '${APP_NAME}':" application.php
rm *.old
popd > /dev/null


mkdir $APP_DIR/lib/pails
cp -r $TOOLS_DIR/../*.php $APP_DIR/lib/pails/
cp -r $TOOLS_DIR/../lib $APP_DIR/lib/pails/



#$GIT_COMMAND https://github.com/jpfuentes2/php-activerecord.git lib/php-activerecord