#!/bin/bash

TOOLS_DIR=`dirname $0`

APP_DIR=.

if [ ! -e config/application.php ]; then
  echo "This is not a pails app"
  exit 1
fi

if [ ! -e lib/activerecord ]; then
  echo "pails-activerecord is required. Install it by running"
  echo "    pails install activerecord"
  echo "However, if you're not using activerecord, you likely don't have any"
  echo "migrations to be run"
  exit 1
fi

if [ ! -e db/migrations ]; then
  echo "Nothing to migrate"
  exit 0
fi

#First, let's see if we need to create the table
php <<EOT
<?php
include('config/application.php');
include('lib/activerecord/ActiveRecord.php');
class MigrationHistory extends ActiveRecord\\Model {}
ActiveRecord\\Config::initialize(function(\$cfg) use (\$CONNECTION_STRINGS)
{
  \$cfg->set_connections(\$CONNECTION_STRINGS);
  \$cfg->set_default_connection('development');
});
\$conn = ActiveRecord\\Connection::instance();
\$conn->query('create table if not exists migration_histories
( id integer not null auto_increment primary key,
migration_id varchar(30) not null,
migration_date datetime
)');
EOT

for file in db/migrations/*.sql ; do
  if [ "$file" = "db/migrations/*.sql" ]; then
    echo "Nothing to migrate"
    exit 0
  fi

  MIGRATION_ID=$(basename $file | cut -d _ -f 1)
  MIGRATION_NAME=$(basename $file .sql)

  MIGRATED_DATE=$(php <<EOT
<?php
  include('config/application.php');
  include('lib/activerecord/ActiveRecord.php');
  class MigrationHistory extends ActiveRecord\\Model {}
  ActiveRecord\Config::initialize(function(\$cfg) use (\$CONNECTION_STRINGS)
  {
    \$cfg->set_connections(\$CONNECTION_STRINGS);
    \$cfg->set_default_connection('development');
  });
  try
  {
    \$migration = MigrationHistory::find_by_migration_id("$MIGRATION_ID");
    echo \$migration != null ? \$migration->migration_date : '';
  }
  catch (Exception \$e)
  {
    echo "";
  }
EOT)

  if [ -z "$MIGRATED_DATE" ]; then
    echo "Applying migration $MIGRATION_NAME"

    php <<EOT
    <?php
    include('config/application.php');
    include('lib/activerecord/ActiveRecord.php');
    class MigrationHistory extends ActiveRecord\\Model {}
    ActiveRecord\\Config::initialize(function(\$cfg) use (\$CONNECTION_STRINGS)
    {
      \$cfg->set_connections(\$CONNECTION_STRINGS);
      \$cfg->set_default_connection('development');
    });
    \$conn = ActiveRecord\\Connection::instance();
    try
    {
      \$conn->query(file_get_contents("$file"));
      MigrationHistory::create(array('migration_id' => '$MIGRATION_ID', 'migration_date' => new DateTime()));
      echo 'SUCCESS';
    }
    catch (Exception \$e)
    {
      echo 'FAILED: '.\$e;
    }
EOT
    echo
  fi
done
