#!/bin/bash

TOOLS_DIR=`dirname $0`

APP_DIR=.

if [ $# -lt 1 ]; then
  echo "Must provide a description for the migration"
  exit 1
fi

DESCRIPTION=$(echo "$@" | tr '[:upper:] ' '[:lower:]_')
DATESTAMP=$(date +%Y%m%d%H%M%S)

touch db/migrations/${DATESTAMP}_${DESCRIPTION}.sql
